"""empty message

Revision ID: a8a9c8116e3d
Revises: 
Create Date: 2025-03-11 13:06:31.242157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8a9c8116e3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('notifications')
    op.drop_table('maintenance_requests')
    op.drop_table('transactions')
    op.drop_table('technician_schedule')
    op.drop_table('apartments')
    op.drop_table('contracts')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('user')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('Owner', 'Administrator', 'Buyer/Tenant', 'Technician'),
               type_=sa.Enum('Administrator', 'Buyer/Tenant', 'Owner', 'Technician'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('role',
               existing_type=sa.Enum('Administrator', 'Buyer/Tenant', 'Owner', 'Technician'),
               type_=mysql.ENUM('Owner', 'Administrator', 'Buyer/Tenant', 'Technician'),
               existing_nullable=False)

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('job', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('facebook_link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('contracts',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('apartment_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('contract_details', mysql.TEXT(), nullable=False),
    sa.Column('signed', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name='contracts_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='contracts_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('apartments',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('location', mysql.TEXT(), nullable=False),
    sa.Column('unit_number', mysql.TEXT(), nullable=False),
    sa.Column('area', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('number_of_rooms', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.ENUM('For Sale', 'For Rent'), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('photos', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('parking_availability', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('video', mysql.TEXT(), nullable=True),
    sa.Column('map_location', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('Available', 'Sold', 'Rented'), server_default=sa.text("'Available'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='apartments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('technician_schedule',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('technician_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('request_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('scheduled_date', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('status', mysql.ENUM('Scheduled', 'Completed', 'Cancelled'), nullable=False),
    sa.Column('cancellation_reason', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], name='technician_schedule_ibfk_2'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name='technician_schedule_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('transactions',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('apartment_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('transaction_type', mysql.ENUM('Rent', 'Sale', 'Maintenance'), nullable=False),
    sa.Column('status', mysql.ENUM('Pending', 'Completed', 'Overdue'), nullable=False),
    sa.Column('payment_method', mysql.ENUM('Visa', 'MasterCard', 'Cash'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name='transactions_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='transactions_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('maintenance_requests',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('apartment_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('technician_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('problem_type', mysql.TEXT(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('images', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('status', mysql.ENUM('Pending', 'In Progress', 'Resolved', 'Cancelled'), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('request_date', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('response', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name='maintenance_requests_ibfk_1'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name='maintenance_requests_ibfk_3'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='maintenance_requests_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notifications',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payments',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('transaction_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('due_date', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('paid_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('status', mysql.ENUM('Pending', 'Completed', 'Overdue'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='payments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
